### ISSUE TITLE
AntennaPod not syncing episodes

### ISSUE THREAD

**Issue by Science4583** [bohwaz/micro-gpodder-server#17]
For some reason the gpodder.net selection in AntennaPod is broken but I can add this server using the Next cloud option. Podcasts subscriptions sync but not the episodes. This is the only error I can find in the error.log and nothing useful in debug.log

```
[27-Jan-2024 01:43:56 UTC] ValueError: The arguments array must contain 6654 items, 0 given in /var/www/html/inc/API.php:55
Stack trace:                                                                    
#0 /var/www/html/inc/API.php(55): vsprintf()                                    
#1 /var/www/html/inc/API.php(378): API->debug()
#2 /var/www/html/index.php(55): API->handleRequest()                            
#3 {main}
```

Not sure if it's related but I also get this error when looking at subscriptions in the webui

```
ErrorException: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/index.php:105
Stack trace:
#0 [internal function]: {closure}()
#1 /var/www/html/index.php(105): htmlspecialchars()
#2 {main}
```

**Comment by bohwaz** [comment]
Should be fixed now, thank you.
