### ISSUE TITLE
Error when setting up from scratch

### ISSUE THREAD

**Issue by tuxcomputers** [bohwaz/micro-gpodder-server#33]
I wiped out my current config and set up the server from scratch, now I am getting an error:
1. Create the user name
2. Open antenna pod
3. Login to the server
4. On create device the following error appears in the server log

![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/7f011d36-b325-4706-bfb8-a180c3c2f81c)

**Comment by rhuneai** [comment]
Same here using 0.3.0.

```
[01-May-2024 13:33:15 UTC] Error: Cannot use object of type stdClass as array in /var/www/server/inc/API.php:422
Stack trace:
#0 /var/www/server/inc/API.php(228): API->devices()
#1 /var/www/server/inc/API.php(381): API->route()
#2 /var/www/server/index.php(81): API->handleRequest()
#3 {main}
[01-May-2024 13:33:15 UTC] Error: Cannot use object of type stdClass as array in /var/www/server/inc/API.php:422
Stack trace:
#0 /var/www/server/inc/API.php(228): API->devices()
#1 /var/www/server/inc/API.php(381): API->route()
#2 /var/www/server/index.php(81): API->handleRequest()
#3 {main}
[01-May-2024 13:33:15 UTC] Array
(
    [0] => Array
        (
            [function] => {closure}
            [args] => Array
                (
                    [0] => Error Object
                        (
                            [message:protected] => Cannot use object of type stdClass as array
                            [string:Error:private] => Error: Cannot use object of type stdClass as array in /var/www/server/inc/API.php:422
Stack trace:
#0 /var/www/server/inc/API.php(228): API->devices()
#1 /var/www/server/inc/API.php(381): API->route()
#2 /var/www/server/index.php(81): API->handleRequest()
#3 {main}
                            [code:protected] => 0
                            [file:protected] => /var/www/server/inc/API.php
                            [line:protected] => 422
                            [trace:Error:private] => Array
                                (
                                    [0] => Array
                                        (
                                            [file] => /var/www/server/inc/API.php
                                            [line] => 228
                                            [function] => devices
                                            [class] => API
                                            [type] => ->
                                        )

                                    [1] => Array
                                        (
                                            [file] => /var/www/server/inc/API.php
                                            [line] => 381
                                            [function] => route
                                            [class] => API
                                            [type] => ->
                                        )

                                    [2] => Array
                                        (
                                            [file] => /var/www/server/index.php
                                            [line] => 81
                                            [function] => handleRequest
                                            [class] => API
                                            [type] => ->
                                        )

                                )

                            [previous:Error:private] =>
                        )

                )

        )

)
```

**Comment by bohwaz** [comment]
Should be good now :)
