### ISSUE TITLE
Error: Object of class stdClass could not be converted to string in /var/www/html/inc/DB.php:38

### ISSUE THREAD

**Issue by weirdvic** [bohwaz/micro-gpodder-server#9]
Hello and thank you for your great work!
I have successfully set up a server with my own doman and synced the subscriptions from AntennaPod.
But when I'm trying to sync subscriptions from gPodder 3.11.1 on my PC, I get an error like this in logs:
```
1702306064.065907 [gpodder.opml] ERROR: Cannot import OPML from URL: https://username:password@my.gpodderdomain.test/subscriptions/username.opml
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/opml.py", line 72, in __init__
    doc = xml.dom.minidom.parse(io.BytesIO(util.urlopen(url).content))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/minidom.py", line 1990, in parse
    return expatbuilder.parse(file)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/expatbuilder.py", line 913, in parse
    result = builder.parseFile(file)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
1702306064.306815 [gpodder.gtkui.desktop.podcastdirectory] WARNING: Ignoring update from old thread
1702306064.317015 [gpodder.gtkui.desktop.podcastdirectory] WARNING: Ignoring update from old thread
1702306110.956072 [gpodder.my] WARNING: Invalid credentials. Disabling gpodder.net.
1702306111.164320 [gpodder.my] WARNING: Invalid credentials. Disabling gpodder.net.
```

So if I log in via browser and try to visit https://username:password@my.gpodderdomain.test/subscriptions/username.opml in there, I get an error mentioned in the title:
```
Error: Object of class stdClass could not be converted to string in /var/www/html/inc/DB.php:38
Stack trace:
#0 /var/www/html/inc/DB.php(38): SQLite3Stmt->execute()
#1 /var/www/html/inc/DB.php(55): DB->simple()
#2 /var/www/html/inc/API.php(181): DB->firstColumn()
#3 /var/www/html/inc/API.php(346): API->requireAuth()
#4 /var/www/html/index.php(44): API->handleRequest()
#5 {main}
```

So somehow syncing from AntennaPod works and I can see subscriptions in sqlite DB on a server but syncing from gPodder seems to be broken.

I'd like to assist you with diagnosing this issue as much as possible.

**Comment by weirdvic** [comment]
I have experimented a little and now can confirm that this is defineteley a gPodder auth problem.
It is possible to login with `cURL` to get sessionid cookie like this:
```
curl -i -u 'username:password' -X POST https://my.gpodderdomain.test/api/2/auth/username/login.json
```
After that I can get my subscriptions with a request like this:
```
curl -i -b 'sessionid=cookie-from-the-first-step' https://my.gpodderdomain.test/subscriptions/username.opml
```
So the problem is that gPodder is trying to use HTTPBasic auth I guess?
